version: '2'
services:
  win10_helper_container:
    build: ./HelperContainer
    stdin_open: true
    tty: true
    volumes:
      - /dev/null:/qemu_host_pty
      - ./HelperContainer/captured_packets.pcap:/captured_packets.pcap
